/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ResetRouteImport } from './routes/_reset'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetForgotPasswordRouteImport } from './routes/_reset/forgot-password'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedNotificationsRouteImport } from './routes/_protected/notifications'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedExploreRouteImport } from './routes/_protected/explore'
import { Route as ProtectedUsernameRouteImport } from './routes/_protected/$username'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ResetResetPasswordTokenRouteImport } from './routes/_reset/reset-password.$token'
import { Route as ProtectedSettingsUsernameRouteImport } from './routes/_protected/settings/username'
import { Route as ProtectedSettingsPasswordRouteImport } from './routes/_protected/settings/password'
import { Route as ProtectedSettingsDeleteRouteImport } from './routes/_protected/settings/delete'
import { Route as ProtectedSettingsAccountRouteImport } from './routes/_protected/settings/account'
import { Route as ProtectedSettingsMeAccountRouteImport } from './routes/_protected/settings/me.account'
import { Route as ProtectedUsernameStatusTweetIdRouteImport } from './routes/_protected/$username_/status.$tweetId'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/_reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetForgotPasswordRoute = ResetForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => ResetRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNotificationsRoute = ProtectedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExploreRoute = ProtectedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsernameRoute = ProtectedUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ResetResetPasswordTokenRoute = ResetResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => ResetRoute,
} as any)
const ProtectedSettingsUsernameRoute =
  ProtectedSettingsUsernameRouteImport.update({
    id: '/username',
    path: '/username',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsPasswordRoute =
  ProtectedSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsDeleteRoute = ProtectedSettingsDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedSettingsAccountRoute =
  ProtectedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsMeAccountRoute =
  ProtectedSettingsMeAccountRouteImport.update({
    id: '/me/account',
    path: '/me/account',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedUsernameStatusTweetIdRoute =
  ProtectedUsernameStatusTweetIdRouteImport.update({
    id: '/$username_/status/$tweetId',
    path: '/$username/status/$tweetId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/$username': typeof ProtectedUsernameRoute
  '/explore': typeof ProtectedExploreRoute
  '/home': typeof ProtectedHomeRoute
  '/notifications': typeof ProtectedNotificationsRoute
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/forgot-password': typeof ResetForgotPasswordRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/delete': typeof ProtectedSettingsDeleteRoute
  '/settings/password': typeof ProtectedSettingsPasswordRoute
  '/settings/username': typeof ProtectedSettingsUsernameRoute
  '/reset-password/$token': typeof ResetResetPasswordTokenRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/$username/status/$tweetId': typeof ProtectedUsernameStatusTweetIdRoute
  '/settings/me/account': typeof ProtectedSettingsMeAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/$username': typeof ProtectedUsernameRoute
  '/explore': typeof ProtectedExploreRoute
  '/home': typeof ProtectedHomeRoute
  '/notifications': typeof ProtectedNotificationsRoute
  '/forgot-password': typeof ResetForgotPasswordRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/delete': typeof ProtectedSettingsDeleteRoute
  '/settings/password': typeof ProtectedSettingsPasswordRoute
  '/settings/username': typeof ProtectedSettingsUsernameRoute
  '/reset-password/$token': typeof ResetResetPasswordTokenRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/$username/status/$tweetId': typeof ProtectedUsernameStatusTweetIdRoute
  '/settings/me/account': typeof ProtectedSettingsMeAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_reset': typeof ResetRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/$username': typeof ProtectedUsernameRoute
  '/_protected/explore': typeof ProtectedExploreRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/notifications': typeof ProtectedNotificationsRoute
  '/_protected/settings': typeof ProtectedSettingsRouteWithChildren
  '/_reset/forgot-password': typeof ResetForgotPasswordRoute
  '/_protected/settings/account': typeof ProtectedSettingsAccountRoute
  '/_protected/settings/delete': typeof ProtectedSettingsDeleteRoute
  '/_protected/settings/password': typeof ProtectedSettingsPasswordRoute
  '/_protected/settings/username': typeof ProtectedSettingsUsernameRoute
  '/_reset/reset-password/$token': typeof ResetResetPasswordTokenRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/$username_/status/$tweetId': typeof ProtectedUsernameStatusTweetIdRoute
  '/_protected/settings/me/account': typeof ProtectedSettingsMeAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/login'
    | '/signup'
    | '/$username'
    | '/explore'
    | '/home'
    | '/notifications'
    | '/settings'
    | '/forgot-password'
    | '/settings/account'
    | '/settings/delete'
    | '/settings/password'
    | '/settings/username'
    | '/reset-password/$token'
    | '/settings/'
    | '/$username/status/$tweetId'
    | '/settings/me/account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/login'
    | '/signup'
    | '/$username'
    | '/explore'
    | '/home'
    | '/notifications'
    | '/forgot-password'
    | '/settings/account'
    | '/settings/delete'
    | '/settings/password'
    | '/settings/username'
    | '/reset-password/$token'
    | '/settings'
    | '/$username/status/$tweetId'
    | '/settings/me/account'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_reset'
    | '/logout'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_protected/$username'
    | '/_protected/explore'
    | '/_protected/home'
    | '/_protected/notifications'
    | '/_protected/settings'
    | '/_reset/forgot-password'
    | '/_protected/settings/account'
    | '/_protected/settings/delete'
    | '/_protected/settings/password'
    | '/_protected/settings/username'
    | '/_reset/reset-password/$token'
    | '/_protected/settings/'
    | '/_protected/$username_/status/$tweetId'
    | '/_protected/settings/me/account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ResetRoute: typeof ResetRouteWithChildren
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_reset': {
      id: '/_reset'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_reset/forgot-password': {
      id: '/_reset/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ResetForgotPasswordRouteImport
      parentRoute: typeof ResetRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/notifications': {
      id: '/_protected/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ProtectedNotificationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/explore': {
      id: '/_protected/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ProtectedExploreRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$username': {
      id: '/_protected/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof ProtectedUsernameRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_reset/reset-password/$token': {
      id: '/_reset/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetResetPasswordTokenRouteImport
      parentRoute: typeof ResetRoute
    }
    '/_protected/settings/username': {
      id: '/_protected/settings/username'
      path: '/username'
      fullPath: '/settings/username'
      preLoaderRoute: typeof ProtectedSettingsUsernameRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/password': {
      id: '/_protected/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof ProtectedSettingsPasswordRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/delete': {
      id: '/_protected/settings/delete'
      path: '/delete'
      fullPath: '/settings/delete'
      preLoaderRoute: typeof ProtectedSettingsDeleteRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/account': {
      id: '/_protected/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ProtectedSettingsAccountRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/me/account': {
      id: '/_protected/settings/me/account'
      path: '/me/account'
      fullPath: '/settings/me/account'
      preLoaderRoute: typeof ProtectedSettingsMeAccountRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/$username_/status/$tweetId': {
      id: '/_protected/$username_/status/$tweetId'
      path: '/$username/status/$tweetId'
      fullPath: '/$username/status/$tweetId'
      preLoaderRoute: typeof ProtectedUsernameStatusTweetIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedSettingsRouteChildren {
  ProtectedSettingsAccountRoute: typeof ProtectedSettingsAccountRoute
  ProtectedSettingsDeleteRoute: typeof ProtectedSettingsDeleteRoute
  ProtectedSettingsPasswordRoute: typeof ProtectedSettingsPasswordRoute
  ProtectedSettingsUsernameRoute: typeof ProtectedSettingsUsernameRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedSettingsMeAccountRoute: typeof ProtectedSettingsMeAccountRoute
}

const ProtectedSettingsRouteChildren: ProtectedSettingsRouteChildren = {
  ProtectedSettingsAccountRoute: ProtectedSettingsAccountRoute,
  ProtectedSettingsDeleteRoute: ProtectedSettingsDeleteRoute,
  ProtectedSettingsPasswordRoute: ProtectedSettingsPasswordRoute,
  ProtectedSettingsUsernameRoute: ProtectedSettingsUsernameRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedSettingsMeAccountRoute: ProtectedSettingsMeAccountRoute,
}

const ProtectedSettingsRouteWithChildren =
  ProtectedSettingsRoute._addFileChildren(ProtectedSettingsRouteChildren)

interface ProtectedRouteChildren {
  ProtectedUsernameRoute: typeof ProtectedUsernameRoute
  ProtectedExploreRoute: typeof ProtectedExploreRoute
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedNotificationsRoute: typeof ProtectedNotificationsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRouteWithChildren
  ProtectedUsernameStatusTweetIdRoute: typeof ProtectedUsernameStatusTweetIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedUsernameRoute: ProtectedUsernameRoute,
  ProtectedExploreRoute: ProtectedExploreRoute,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedNotificationsRoute: ProtectedNotificationsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRouteWithChildren,
  ProtectedUsernameStatusTweetIdRoute: ProtectedUsernameStatusTweetIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ResetRouteChildren {
  ResetForgotPasswordRoute: typeof ResetForgotPasswordRoute
  ResetResetPasswordTokenRoute: typeof ResetResetPasswordTokenRoute
}

const ResetRouteChildren: ResetRouteChildren = {
  ResetForgotPasswordRoute: ResetForgotPasswordRoute,
  ResetResetPasswordTokenRoute: ResetResetPasswordTokenRoute,
}

const ResetRouteWithChildren = ResetRoute._addFileChildren(ResetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ResetRoute: ResetRouteWithChildren,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
