/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedNotificationsRouteImport } from './routes/_protected/notifications'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedExploreRouteImport } from './routes/_protected/explore'
import { Route as ProtectedComposeRouteImport } from './routes/_protected/compose'
import { Route as ProtectedBookmarksRouteImport } from './routes/_protected/bookmarks'
import { Route as ProtectedUsernameRouteImport } from './routes/_protected/$username'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedSettingsUsernameRouteImport } from './routes/_protected/settings/username'
import { Route as ProtectedSettingsPasswordRouteImport } from './routes/_protected/settings/password'
import { Route as ProtectedSettingsDeleteRouteImport } from './routes/_protected/settings/delete'
import { Route as ProtectedSettingsAccountRouteImport } from './routes/_protected/settings/account'
import { Route as ProtectedComposePostRouteImport } from './routes/_protected/compose/post'
import { Route as ProtectedSettingsMeAccountRouteImport } from './routes/_protected/settings/me.account'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNotificationsRoute = ProtectedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExploreRoute = ProtectedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedComposeRoute = ProtectedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBookmarksRoute = ProtectedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsernameRoute = ProtectedUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedSettingsUsernameRoute =
  ProtectedSettingsUsernameRouteImport.update({
    id: '/username',
    path: '/username',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsPasswordRoute =
  ProtectedSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsDeleteRoute = ProtectedSettingsDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedSettingsAccountRoute =
  ProtectedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedComposePostRoute = ProtectedComposePostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => ProtectedComposeRoute,
} as any)
const ProtectedSettingsMeAccountRoute =
  ProtectedSettingsMeAccountRouteImport.update({
    id: '/me/account',
    path: '/me/account',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/logout': typeof LogoutRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/$username': typeof ProtectedUsernameRoute
  '/bookmarks': typeof ProtectedBookmarksRoute
  '/compose': typeof ProtectedComposeRouteWithChildren
  '/explore': typeof ProtectedExploreRoute
  '/home': typeof ProtectedHomeRoute
  '/notifications': typeof ProtectedNotificationsRoute
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/compose/post': typeof ProtectedComposePostRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/delete': typeof ProtectedSettingsDeleteRoute
  '/settings/password': typeof ProtectedSettingsPasswordRoute
  '/settings/username': typeof ProtectedSettingsUsernameRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/settings/me/account': typeof ProtectedSettingsMeAccountRoute
}
export interface FileRoutesByTo {
  '/logout': typeof LogoutRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/$username': typeof ProtectedUsernameRoute
  '/bookmarks': typeof ProtectedBookmarksRoute
  '/compose': typeof ProtectedComposeRouteWithChildren
  '/explore': typeof ProtectedExploreRoute
  '/home': typeof ProtectedHomeRoute
  '/notifications': typeof ProtectedNotificationsRoute
  '/compose/post': typeof ProtectedComposePostRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/delete': typeof ProtectedSettingsDeleteRoute
  '/settings/password': typeof ProtectedSettingsPasswordRoute
  '/settings/username': typeof ProtectedSettingsUsernameRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/settings/me/account': typeof ProtectedSettingsMeAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/$username': typeof ProtectedUsernameRoute
  '/_protected/bookmarks': typeof ProtectedBookmarksRoute
  '/_protected/compose': typeof ProtectedComposeRouteWithChildren
  '/_protected/explore': typeof ProtectedExploreRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/notifications': typeof ProtectedNotificationsRoute
  '/_protected/settings': typeof ProtectedSettingsRouteWithChildren
  '/_protected/compose/post': typeof ProtectedComposePostRoute
  '/_protected/settings/account': typeof ProtectedSettingsAccountRoute
  '/_protected/settings/delete': typeof ProtectedSettingsDeleteRoute
  '/_protected/settings/password': typeof ProtectedSettingsPasswordRoute
  '/_protected/settings/username': typeof ProtectedSettingsUsernameRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/settings/me/account': typeof ProtectedSettingsMeAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/logout'
    | '/login'
    | '/signup'
    | '/$username'
    | '/bookmarks'
    | '/compose'
    | '/explore'
    | '/home'
    | '/notifications'
    | '/settings'
    | '/compose/post'
    | '/settings/account'
    | '/settings/delete'
    | '/settings/password'
    | '/settings/username'
    | '/settings/'
    | '/settings/me/account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logout'
    | '/login'
    | '/signup'
    | '/$username'
    | '/bookmarks'
    | '/compose'
    | '/explore'
    | '/home'
    | '/notifications'
    | '/compose/post'
    | '/settings/account'
    | '/settings/delete'
    | '/settings/password'
    | '/settings/username'
    | '/settings'
    | '/settings/me/account'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/logout'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_protected/$username'
    | '/_protected/bookmarks'
    | '/_protected/compose'
    | '/_protected/explore'
    | '/_protected/home'
    | '/_protected/notifications'
    | '/_protected/settings'
    | '/_protected/compose/post'
    | '/_protected/settings/account'
    | '/_protected/settings/delete'
    | '/_protected/settings/password'
    | '/_protected/settings/username'
    | '/_protected/settings/'
    | '/_protected/settings/me/account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/notifications': {
      id: '/_protected/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ProtectedNotificationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/explore': {
      id: '/_protected/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ProtectedExploreRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/compose': {
      id: '/_protected/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ProtectedComposeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/bookmarks': {
      id: '/_protected/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof ProtectedBookmarksRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$username': {
      id: '/_protected/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof ProtectedUsernameRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/username': {
      id: '/_protected/settings/username'
      path: '/username'
      fullPath: '/settings/username'
      preLoaderRoute: typeof ProtectedSettingsUsernameRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/password': {
      id: '/_protected/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof ProtectedSettingsPasswordRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/delete': {
      id: '/_protected/settings/delete'
      path: '/delete'
      fullPath: '/settings/delete'
      preLoaderRoute: typeof ProtectedSettingsDeleteRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/account': {
      id: '/_protected/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ProtectedSettingsAccountRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/compose/post': {
      id: '/_protected/compose/post'
      path: '/post'
      fullPath: '/compose/post'
      preLoaderRoute: typeof ProtectedComposePostRouteImport
      parentRoute: typeof ProtectedComposeRoute
    }
    '/_protected/settings/me/account': {
      id: '/_protected/settings/me/account'
      path: '/me/account'
      fullPath: '/settings/me/account'
      preLoaderRoute: typeof ProtectedSettingsMeAccountRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedComposeRouteChildren {
  ProtectedComposePostRoute: typeof ProtectedComposePostRoute
}

const ProtectedComposeRouteChildren: ProtectedComposeRouteChildren = {
  ProtectedComposePostRoute: ProtectedComposePostRoute,
}

const ProtectedComposeRouteWithChildren =
  ProtectedComposeRoute._addFileChildren(ProtectedComposeRouteChildren)

interface ProtectedSettingsRouteChildren {
  ProtectedSettingsAccountRoute: typeof ProtectedSettingsAccountRoute
  ProtectedSettingsDeleteRoute: typeof ProtectedSettingsDeleteRoute
  ProtectedSettingsPasswordRoute: typeof ProtectedSettingsPasswordRoute
  ProtectedSettingsUsernameRoute: typeof ProtectedSettingsUsernameRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedSettingsMeAccountRoute: typeof ProtectedSettingsMeAccountRoute
}

const ProtectedSettingsRouteChildren: ProtectedSettingsRouteChildren = {
  ProtectedSettingsAccountRoute: ProtectedSettingsAccountRoute,
  ProtectedSettingsDeleteRoute: ProtectedSettingsDeleteRoute,
  ProtectedSettingsPasswordRoute: ProtectedSettingsPasswordRoute,
  ProtectedSettingsUsernameRoute: ProtectedSettingsUsernameRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedSettingsMeAccountRoute: ProtectedSettingsMeAccountRoute,
}

const ProtectedSettingsRouteWithChildren =
  ProtectedSettingsRoute._addFileChildren(ProtectedSettingsRouteChildren)

interface ProtectedRouteChildren {
  ProtectedUsernameRoute: typeof ProtectedUsernameRoute
  ProtectedBookmarksRoute: typeof ProtectedBookmarksRoute
  ProtectedComposeRoute: typeof ProtectedComposeRouteWithChildren
  ProtectedExploreRoute: typeof ProtectedExploreRoute
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedNotificationsRoute: typeof ProtectedNotificationsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedUsernameRoute: ProtectedUsernameRoute,
  ProtectedBookmarksRoute: ProtectedBookmarksRoute,
  ProtectedComposeRoute: ProtectedComposeRouteWithChildren,
  ProtectedExploreRoute: ProtectedExploreRoute,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedNotificationsRoute: ProtectedNotificationsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
